### ISSUE TITLE
Preparing for packaging AzPainter 2.1.1

### ISSUE THREAD

**Issue by Symbian9** [Symbian9/azpainter#23]
**AzPainter 2.1.1** (with fixed locales)
* https://github.com/Symbian9/azpainter/releases/tag/v2.1.1

**PACKAGING STATUS:**
AppImage (from `master`): [![Build status](https://travis-ci.org/Symbian9/azpainter.svg?branch=master)](https://travis-ci.org/Symbian9/azpainter)

[![Packaging status](https://repology.org/badge/vertical-allrepos/azpainter.svg)](https://repology.org/metapackage/azpainter)

**TODO:**

Travis-CI autobuild
* [ ] Linux-based (.AppImage)
  * [x] setup autobuilds using Travis CI 
    * [ ] upload resulted binary in "Releases"
    * [ ] setup autoupload resulted binary in "Releases"

Cast @AlexanderP
* [x] Debian (.deb)
  * http://notesalexp.org/packages/en/jessie/amd64/azpainter/
* [x] Ubuntu (.deb)
  * https://launchpad.net/~alex-p/+archive/ubuntu/azpainter

Cast @abcang
* [x] macOS (.dmg)
  * https://github.com/abcang/azpainter-mac/issues/8

Cast @danfe
* [x] FreeBSD (ports)
  * http://www.freshports.org/graphics/azpainter

Cast @aevseev
* [ ] CentOS (.rpm)
  * http://download.opensuse.org/repositories/home:/aevseev/

P.S.: Unknown users
* [x] Arch Linux (AUR)
  * https://aur.archlinux.org/packages/azpainter/
* [ ] Gentoo (.ebuild)
  * https://gpo.zugaina.org/media-gfx/azpainter
* [x] MX Linux (.deb)
  * http://mxrepo.com/mx/testrepo/pool/test/a/azpainter/
* [x] Puppy Linux (.pet/.sfs)
  * http://www.murga-linux.com/puppy/viewtopic.php?t=95329
* [ ] Slackware (.tgz/.txz)
* [ ] SliTaZ (.tazpkg)
  * http://forum.slitaz.org/topic/azpainter-why-it-isnt-in-slitaz-repositories
* [ ] Void Linux (.xbps)

**REFERENCE:**
* https://repology.org/metapackage/azpainter/versions
* https://pkgs.org/download/azpainter
* https://www.linux.org.ru/forum/multimedia/13223232

**Comment by Symbian9** [comment]
> bidulock commented on 2017-09-23 07:34
> 
> Need to add libxfixes to makedepends to build in a clean chroot.
> 
> https://aur.archlinux.org/packages/azpainter

Anybody could explain me what need fix in `master`?
*

**Comment by danfe** [comment]
I've updated FreeBSD port; did not find any typos/mistakes in the latest translations.

**Comment by Symbian9** [comment]
macOS port ready!
- https://github.com/abcang/azpainter-mac/releases/tag/2.1.0

https://twitter.com/abcang1015/status/943838453506088960
