### ISSUE TITLE
Translating AzPainter 2.1.2

### ISSUE THREAD

**Issue by Symbian9** [Symbian9/azpainter#36]
*AzPainter 2.1.2* released (2018/04/19)

- https://osdn.net/projects/azpainter/releases/69408
  - http://osdn.dl.osdn.jp/azpainter/69408/azpainter-2.1.2.tar.xz

### FAQ

- https://github.com/Symbian9/azpainter/blob/master/translation/HOWTO_en

Translation template (`en` is plain text file; in English)

- https://github.com/Symbian9/azpainter/blob/master/translation/en

Language ID (translation; locale)

- http://www.localeplanet.com/icu/

### TODO

- [ ] Add new locales
  - [ ] `fr`
- [x] Check existed locales
  - [x] `en`
    - Fixed already
  - [x] `ja` (original locale)
    - Fixed already
  - [x] `pt_BR`
    - No changes
  - [x] `ru`
    - Fixed already
  - [x] `uk`
    - Fixed alredy
  - [x] `zh_CN`
    - Fixed already
      - https://github.com/Symbian9/azpainter/commit/54a0c60e1c10c710551fe73eabaa07edb37dff98
- [x] Check new locales
  - [x] `be`
    - Depend on https://github.com/Symbian9/azpainter/issues/35
  - [ ] `be`
    - Depend on https://github.com/Symbian9/azpainter/issues/36#issuecomment-386305965
    - Patch available https://github.com/Symbian9/azpainter/files/1971195/be.txt
- [x] Update locales in `master` branch
  - https://github.com/Symbian9/azpainter/tree/master/translation
    - https://github.com/Symbian9/azpainter/commit/70f9c02ecc6b982354b75e6842965d60940c1861
- [x] Update `AUTHORS`
  - https://github.com/Symbian9/azpainter/blob/master/AUTHORS
    - https://github.com/Symbian9/azpainter/commit/54a0c60e1c10c710551fe73eabaa07edb37dff98

**Comment by Symbian9** [comment]
Cast @danfe

**Comment by Symbian9** [comment]
Updated: https://github.com/Symbian9/azpainter/commit/70f9c02ecc6b982354b75e6842965d60940c1861

**Comment by Symbian9** [comment]
@danfe & @antikruk, I near forgot to add your names to `AUTHORS`

- https://github.com/Symbian9/azpainter/blob/master/AUTHORS

How should I write your names? As this:

```
 # translation
-------------------

be
    Antikruk, 2018

en
    Alexey Dokuchaev, 2018
    Eugeniy Fedirets <evgeniy_fedirets@ukr.net>, 2017-2018

pt_BR
    Adriano Duarte

ru
    Alexey Dokuchaev, 2018
    Eugeniy Fedirets <evgeniy_fedirets@ukr.net>, 2017-2018
    Alexandre Prokoudine <alexandre.prokoudine@gmail.com>, 2017

uk
    Eugeniy Fedirets <evgeniy_fedirets@ukr.net>, 2017-2018

zh_CN
    Senlin
```

Or how should I wrote your names here?

**Comment by danfe** [comment]
Looks good enough to me.

**Comment by Symbian9** [comment]
@antikruk &, @danfe & @SenlinOS, file `AUTHORS` just updated:

- https://github.com/Symbian9/azpainter/commit/54a0c60e1c10c710551fe73eabaa07edb37dff98

*Azel* already respond to me via email and promise that she would merge those fixed locales in original repository too ;-)

> Thank you!
> Add the locale, if there is a next update.
>
> Azel <azelpg@gmail.com>
> 24.04.2018, 02:10

P.S: This issue left open for other translators, but on next release I will open new issue & call all of you on next round of translation too!

**Comment by antikruk** [comment]
Hi, I found some inaccuracies. Fixed
[be.txt](https://github.com/Symbian9/azpainter/files/1971195/be.txt)

**Comment by RavengamerSpace** [comment]
I can do the translation for the french language

**Comment by danfe** [comment]
@RavengamerSpace Certainly, please do!

**Comment by RavengamerSpace** [comment]
@Symbian9 I'm a newcomer. So you can teach me things :-)

**Comment by Symbian9** [comment]
> I'm a newcomer. So you can teach me things :-)

@RavengamerSpace, lets make it simple for you!

Firstly, just download file `en` (it is simple text file)

- Direct link: https://raw.githubusercontent.com/Symbian9/azpainter/master/translation/en

Then open it in your text editor (Notepad++, Geany, etc.) and translate all strings to **French**.

When you finish translating save it as file `fr.txt` and attach to the your next comment.

That's all ;-)

P.S.: Rest of the work (pulling it to `master` branch) I will do by myself.

**Comment by Symbian9** [comment]
@RavengamerSpace, any news on translating to French?

**Comment by RavengamerSpace** [comment]
Hi @Symbian9 
Yeah, I've started the translation.
But actually I'm in vacation, so I can't do it.
Sorry

**Comment by Symbian9** [comment]
@RavengamerSpace, any progress on French locale?

**Comment by RavengamerSpace** [comment]
@Symbian9 Hi, I'm sorry but as a student I don't have a lot of time but I will try to produce something at the end of this week

**Comment by Symbian9** [comment]
### Translating AzPainter 2.1.3

- https://github.com/Symbian9/azpainter/issues/45
