### ISSUE TITLE
Packaging AzPainter 2.1.2

### ISSUE THREAD

**Issue by Symbian9** [Symbian9/azpainter#37]
**AzPainter 2.1.2** released (with fixed locales)

- https://github.com/Symbian9/azpainter/releases/tag/v2.1.2

### PACKAGING STATUS

AppImage (from `master`): [![Build status](https://travis-ci.org/Symbian9/azpainter.svg?branch=master)](https://travis-ci.org/Symbian9/azpainter)

[![Packaging status](https://repology.org/badge/vertical-allrepos/azpainter.svg)](https://repology.org/metapackage/azpainter)

### TODO

Travis-CI autobuild
* [ ] Linux-based (.AppImage)
  * [x] setup autobuilds using Travis CI 
    * [ ] upload resulted binary in "Releases"
    * [ ] setup autoupload resulted binary in "Releases"

Cast @AlexanderP
* [ ] Debian (.deb)
  * http://notesalexp.org/packages/en/jessie/amd64/azpainter/
* [ ] Ubuntu (.deb)
  * https://launchpad.net/~alex-p/+archive/ubuntu/azpainter

Cast @abcang
* [ ] macOS (.dmg)
  * https://github.com/abcang/azpainter-mac/issues/

Cast @danfe
* [ ] FreeBSD (ports)
  * http://www.freshports.org/graphics/azpainter

Cast @aevseev
* [ ] CentOS (.rpm)
  * http://download.opensuse.org/repositories/home:/aevseev/

P.S.: Unknown users
* [ ] Arch Linux (AUR)
  * https://aur.archlinux.org/packages/azpainter/
* [ ] Gentoo (.ebuild)
  * https://gpo.zugaina.org/media-gfx/azpainter
* [ ] MX Linux (.deb)
  * http://mxrepo.com/mx/testrepo/pool/test/a/azpainter/
* [ ] Puppy Linux (.pet/.sfs)
  * http://www.murga-linux.com/puppy/viewtopic.php?t=95329
* [ ] Slackware (.tgz/.txz)
* [ ] SliTaZ (.tazpkg)
  * http://forum.slitaz.org/topic/azpainter-why-it-isnt-in-slitaz-repositories
* [ ] Void Linux (.xbps)

**REFERENCE:**
* https://repology.org/metapackage/azpainter/versions
* https://pkgs.org/download/azpainter
* https://www.linux.org.ru/forum/multimedia/13223232

**Comment by danfe** [comment]
FreeBSD port updated and Belarusian locale added.  Looks like locate patches for previous version were not included in this one for some reason...

**Comment by Symbian9** [comment]
> Looks like locate patches for previous version were not included in this one for some reason...

@danfe, what you mean?

- https://github.com/Symbian9/azpainter/issues/36

Locales in this repo (https://github.com/Symbian9/azpainter/) fixed already.

But in offcial repo (https://osdn.net/projects/azpainter/) they not yet implemented, so I will ask *Azel* for adding them in official repo too.

**Comment by Symbian9** [comment]
> FreeBSD port updated and Belarusian locale added.

@danfe, Thank you! ;-)

Funny, that on Repology it still show previous version of ports, but on Freshports I can see latest build

- https://repology.org/metapackage/azpainter/versions
- https://www.freshports.org/graphics/azpainter

Anyway, I already update manually info about builds for BSD-based OS on the Wiki page

- https://github.com/Symbian9/azpainter/wiki/Packaging-status

**Comment by danfe** [comment]
Yes, I was talking about Azel's official tarballs (the ones from OSDN).  Obviously, your own repo should contain all the recent changes. :-)

Yes, please ask her to add them.  There was quite a large time gap between two recent releases, and I was a bit surprized to see that I still need to carry locale patches from 2.1.1.

**Comment by Symbian9** [comment]
> and I was a bit surprized to see that I still need to carry locale patches from 2.1.1.

@danfe, why you not use for packaging only source releases from https://github.com/Symbian9/azpainter/ directly? This repo already include "latest official code + fixed locales + patches".

P.S.: I'm in touch with *Azel*, so this Github repo is "near-official patched mirror" of OSDN repo ;-)
