### ISSUE TITLE
Translating AzPainter 2.1.3

### ISSUE THREAD

**Issue by Symbian9** [Symbian9/azpainter#45]
*AzPainter 2.1.3* released (2018/10/06)

- https://osdn.net/projects/azpainter/releases/70132
  - http://osdn.dl.osdn.jp/azpainter/70132/azpainter-2.1.3.tar.xz
- https://github.com/Symbian9/azpainter/tree/release

### FAQ

- https://github.com/Symbian9/azpainter/blob/master/translation/HOWTO_en

Translation template (`en` is plain text file; in English)

- https://github.com/Symbian9/azpainter/blob/release/translation/en

Language ID (translation; locale) naming:

- http://www.localeplanet.com/icu/

### TODO

- [ ] Check existed locales
  - [x] `en` | original locale by *Azel* with fixes by *me*: **this is translation template**!
    - **New lines**:
      - https://github.com/Symbian9/azpainter/blob/release/translation/en#L485
      - https://github.com/Symbian9/azpainter/blob/release/translation/en#L754
      - https://github.com/Symbian9/azpainter/blob/release/translation/en#L755
      - https://github.com/Symbian9/azpainter/blob/release/translation/en#L765
      - https://github.com/Symbian9/azpainter/blob/release/translation/en#L766
      - https://github.com/Symbian9/azpainter/blob/release/translation/en#L767
      - https://github.com/Symbian9/azpainter/blob/release/translation/en#L1101
    - **Removed lines**:
      - White space line removed after: https://github.com/Symbian9/azpainter/blob/release/translation/en#L1099
    - **Fixed lines**:
      - `+=[palette]\nRight click/Ctrl+left click: regist color` --> `+=[palette]\nRight click/Ctrl+left click: register color`: https://github.com/Symbian9/azpainter/blob/release/translation/en#L602
      - `+=RGB ...` --> `+=RGB adjustment...`:  https://github.com/Symbian9/azpainter/blob/release/translation/en#L1175
  - [x] `ja` | original locale by *Azel*
  - [ ] `pt_BR`
  - [x] `ru` | Cast @danfe
    - https://github.com/Symbian9/azpainter/issues/45#issuecomment-439697937
  - [x] `uk` | *me*
  - [x] `zh_CN` | Cast @SenlinOS
    - https://github.com/Symbian9/azpainter/issues/44
  - [x] `be` | Cast @antikruk
    - https://github.com/Symbian9/azpainter/issues/45#issuecomment-438671644
      - https://github.com/Symbian9/azpainter/files/2580984/be.txt
- [ ] Add new locales
  - [x] `es_ES`
  - [ ] `fr` | Cast @RavengamerSpace
- [ ] Update locales in `master` branch
  - https://github.com/Symbian9/azpainter/tree/master/translation
- [ ] Update `AUTHORS`
  - https://github.com/Symbian9/azpainter/blob/master/AUTHORS

> *NOTE*: Currently working branch is `release`, so firstly all patches should be included in `release` branch and then I will merge it in `master`.
>
> - https://github.com/Symbian9/azpainter/tree/release/translation/
>
> Then we will start to work on packaging.

**Comment by danfe** [comment]
Looks like [Belarusian locale fixes](https://github.com/Symbian9/azpainter/issues/36#issuecomment-386305965) are still not committed.

**Comment by danfe** [comment]
I didn't find any mistakes or typos in the Russian translation, you check that box.  FreeBSD port was updated to version 2.1.3 and also includes the latest fixes to Belarusian and Chinese translations.

**Comment by antikruk** [comment]
> > Looks like Belarusian locale fixes are still not committed.
> 
> Those fixes (related to `2.1.2`) merged now into `release` branch:
> 
> * [e43f3fb](https://github.com/Symbian9/azpainter/commit/e43f3fbb1af3359b2a1107e2b395ded4a32adac5)
> 
> But fixes related to `2.1.3` still needed, @antikruk.

Sorry, i don't understand. I have to confirm it, or a new version has been modified?

**Comment by Symbian9** [comment]
> I didn't find any mistakes or typos in the Russian translation

**Few new strings added in locale template** of *AzPainter* `2.1.3`!

Try compare `en` locale in `2.1.2` and `2.1.3` versions.

**Comment by Symbian9** [comment]
> Sorry, i don't understand. I have to confirm it, or a new version has been modified?

@antikruk, there are few new strings, read my [previous comment](https://github.com/Symbian9/azpainter/issues/45#issuecomment-438315103) (few new functions added in `2.1.3`)

**Comment by antikruk** [comment]
> > Sorry, i don't understand. I have to confirm it, or a new version has been modified?
> 
> @antikruk, there are few new strings in locales template added for `2.1.3`, read my [previous comment](https://github.com/Symbian9/azpainter/issues/45#issuecomment-438315103) (few new functions added in `2.1.3`)
Ok. I understand. tomorrow I will update the translation

**Comment by antikruk** [comment]
> > > Sorry, i don't understand. I have to confirm it, or a new version has been modified?
> > 
> > 
> > @antikruk, there are few new strings in locales template added for `2.1.3`, read my [previous comment](https://github.com/Symbian9/azpainter/issues/45#issuecomment-438315103) (few new functions added in `2.1.3`)
> 
> Ok. I understand. tomorrow I will update the translation

Done
[be.txt](https://github.com/Symbian9/azpainter/files/2579489/be.txt)

**Comment by Symbian9** [comment]
> Done
> 
> - https://github.com/Symbian9/azpainter/files/2579489/be.txt

Huh, to be clear, this is still incomplete :-(

Why you remove near all content in `[2015]`?

![pic.1](http://i.imgur.com/aCoxXNJ.png)

Also, you add only 1 new string...

![pic.2](http://i.imgur.com/Gb7DqhA.png)

Translation template (`en` file) for `2.1.3` include next changes:

- New lines:
  - https://github.com/Symbian9/azpainter/blob/release/translation/en#L485
  - https://github.com/Symbian9/azpainter/blob/release/translation/en#L754
  - https://github.com/Symbian9/azpainter/blob/release/translation/en#L755
  - https://github.com/Symbian9/azpainter/blob/release/translation/en#L765
  - https://github.com/Symbian9/azpainter/blob/release/translation/en#L766
  - https://github.com/Symbian9/azpainter/blob/release/translation/en#L767
 - https://github.com/Symbian9/azpainter/blob/release/translation/en#L1101
- Edited lines:
  - `+=[palette]\nRight click/Ctrl+left click: register color` --> `+=[palette]\nRight click/Ctrl+left click: register color`: https://github.com/Symbian9/azpainter/blob/release/translation/en#L602
  - `+=RGB ...` --> `+=RGB adjustment...`:  https://github.com/Symbian9/azpainter/blob/release/translation/en#L1175
- Removed lines:
  - White space removed after: https://github.com/Symbian9/azpainter/blob/release/translation/en#L1099

P.S.: I just add this info into header of this issue.

**Comment by antikruk** [comment]
> > Done
> > 
> > * https://github.com/Symbian9/azpainter/files/2579489/be.txt
> 
> @antikruk, to be clear, this is still incomplete :-(
> 
> Why you remove all content in `[2015]`?
> 
> ![pic.1](https://camo.githubusercontent.com/2bc26a46f85ca4d7e916e2012643c54e9835e8b7/687474703a2f2f692e696d6775722e636f6d2f61436f78584e4a2e706e67)
> 
> Also, you add only 1 new string...
> 
> ![pic.2](https://camo.githubusercontent.com/ef69e41da92cce56bcb55a19b65a25d1efefc685/687474703a2f2f692e696d6775722e636f6d2f476237447168412e706e67)
> 
> Translation template (`en` file) for `2.1.3` (currently `release` branch) include next changes:
> 
> * [10473c7](https://github.com/Symbian9/azpainter/commit/10473c7841c5bd8a391ba8db9455069161e04ae1)
>   
>   * New lines:
>     
>     * https://github.com/Symbian9/azpainter/blob/release/translation/en#L485
>     * https://github.com/Symbian9/azpainter/blob/release/translation/en#L754
>     * https://github.com/Symbian9/azpainter/blob/release/translation/en#L755
>     * https://github.com/Symbian9/azpainter/blob/release/translation/en#L765
>     * https://github.com/Symbian9/azpainter/blob/release/translation/en#L766
>     * https://github.com/Symbian9/azpainter/blob/release/translation/en#L767
>     * https://github.com/Symbian9/azpainter/blob/release/translation/en#L1101
>   * Removed lines:
>     
>     * White space removed after: https://github.com/Symbian9/azpainter/blob/release/translation/en#L1099
> 
> Also, next fixes added into `master` branch earlier:
> 
> * Edited lines:
>   
>   * `+=[palette]\nRight click/Ctrl+left click: regist color` --> `+=[palette]\nRight click/Ctrl+left click: register color`: https://github.com/Symbian9/azpainter/blob/release/translation/en#L602
>   * `+=RGB ...` --> `+=RGB adjustment...`:  https://github.com/Symbian9/azpainter/blob/release/translation/en#L1175
> 
> > I didn't find any mistakes or typos in the Russian translation, you check that box.
> 
> @danfe, check `ru` now and follow changes in `en`.
> 
> P.S.: I just add this info into header of this issue.

Hm, OmegaT has corrupted markup. Check it, please
[be.txt](https://github.com/Symbian9/azpainter/files/2580984/be.txt)

**Comment by Symbian9** [comment]
Ukrainian locale (`uk`) now ready for *AzPainter* `2.1.3` ;-)

- https://github.com/Symbian9/azpainter/commit/ce652fa7f8bbe1f53e8398c12c5fb1ab48431823

**Comment by danfe** [comment]
Oh, I see, a few strings were indeed missing, attaching a patch.  I've compared it to your Ukrainian version, there are two differences: I didn't use elaborate version of "replace and insert horizontally", IMHO it's overly long and simple "replace (horizontally)" is sufficient.  Second, in that context, "minimize" means "minimize window to the taskbar", so I've used more common term for it.  Now, because I cannot attach a diff (//Preview// button also does not work, stupid GitHub), I'm posting it here inline (sorry):
```diff
--- translation/ru.orig
+++ translation/ru
@@ -750,6 +750,8 @@
 +=Интерлиньяж
 +=Рисовать текст вертикально
 +=Сглаживание
++=Использовать DPI монитора
++=U+309B/U+309C
 100=По умолчанию
 +=Отсутствует
 +=Обычное
@@ -759,6 +761,9 @@
 120=Нормальный
 +=Курсив
 +=Наклонный
+130=Как есть
++=Заменить на U+3099/U+309A
++=Заменить (горизонтально)

 #-----------------------
 # Shortcut key setting
@@ -1091,8 +1096,8 @@
 +=Сохранить копию(&D)...
 +=Недавние файлы(&R)
 +=Выход(&X)
-
 +=Очистить историю(&C)
++=Свернуть(&M)

 ### edit - Меню "Правка(E)"
 2000=Отменить(&Z)
```
P.S.  There is a missing space before `(` in the Belarusian translation on line 815.

**Comment by Symbian9** [comment]
> Oh, I see, a few strings were indeed missing, attaching a patch.

I will update `ru` and fix `uk` & `be` in `release` branch. Thanks, @danfe ;-)
