### ISSUE TITLE
Packaging AzPainter 2.1.3

### ISSUE THREAD

**Issue by Symbian9** [Symbian9/azpainter#48]
**AzPainter 2.1.3** released (with fixed locales)

- https://github.com/Symbian9/azpainter/releases/tag/v2.1.3

### PACKAGING STATUS

- https://github.com/Symbian9/azpainter/wiki/Packaging-status

### TODO

Cast *MX Linux* maintainers
- [x] MX Linux (.deb)
    - https://forum.mxlinux.org/viewtopic.php?f=55&t=44900

Cast @abcang
- [x] macOS
  - https://github.com/abcang/azpainter-mac
  - https://github.com/abcang/homebrew-azpainter

Cast @AlexanderP
- [x] Debian (.deb)
  - http://notesalexp.org/packages/en/jessie/amd64/azpainter/
- [x] Ubuntu (.deb)
  - https://launchpad.net/~alex-p/+archive/ubuntu/azpainter

Cast @danfe
- [x] FreeBSD (ports)
  - http://www.freshports.org/graphics/azpainter

Cast @void-linux
- [x] Void Linux (.xbps)
  - https://github.com/void-linux/void-packages/tree/master/srcpkgs/azpainter

Cast @AOSC-Dev
- [ ] AOSC
  - https://packages.aosc.io/packages/azpainter
  - https://github.com/AOSC-Dev/aosc-os-abbs/tree/testing/extra-creativity/azpainter

Cast @aevseev
- [ ] CentOS, OpenSUSE, SLE (.rpm)
  - https://software.opensuse.org/download.html?project=home:aevseev&package=azpainter

Cast @macports
- [ ] Mac OS (ports)
  - [ ] https://github.com/macports/macports-ports/blob/master/graphics/azpainter/Portfile

***

Cast (?)
- [x] Arch Linux (AUR)
  - https://aur.archlinux.org/packages/azpainter/

Cast (?)
- [x] Gentoo (.ebuild)
  - https://gpo.zugaina.org/media-gfx/azpainter

Cast (?)
- [ ] Puppy Linux (.pet/.sfs)
  - http://www.murga-linux.com/puppy/viewtopic.php?t=95329

Cast (?)
- [ ] SliTaZ (.tazpkg)
  - http://forum.slitaz.org/topic/azpainter-why-it-isnt-in-slitaz-repositories

Cast (?)
- [ ] Slackware (.tgz/.txz)

### REFERENCES

- https://repology.org/metapackage/azpainter/versions
- https://www.linux.org.ru/forum/multimedia/13223232

**Comment by Symbian9** [comment]
AzPainter 2.1.4 ready for packaging

- https://github.com/Symbian9/azpainter/issues/63
