### ISSUE TITLE
Translating AzPainter 2.1.4

### ISSUE THREAD

**Issue by Symbian9** [Symbian9/azpainter#58]
*AzPainter 2.1.4* released (2019/05/01)

- https://osdn.net/projects/azpainter/releases/71051
  - http://osdn.dl.osdn.jp/azpainter/71501/azpainter-2.1.4.tar.xz
- https://github.com/Symbian9/azpainter/tree/release

### FAQ

- https://github.com/Symbian9/azpainter/blob/master/translation/HOWTO_en

Translation template (`en` is plain text file; in English)

- https://github.com/Symbian9/azpainter/blob/release/translation/en

Language ID (translation; locale) naming:

- http://www.localeplanet.com/icu/

> **NOTE**: Currently working branch is `release`, so firstly all patches should be included in `release` branch and then I will merge it in `master`.
>
> - https://github.com/Symbian9/azpainter/tree/release/translation/
>
> Then we will start to work on packaging.

### TODO

> **ATTENTION**: Translation files should NOT include "white spaces"! Check it using `grep`:.
> 
> ```
> $ grep -n '[[:blank:]]$'
> ```

- [ ] Check existed locales
  - [x] `en` | original locale by *Azel* with fixes by *me*: **this is translation template**!
    - **New lines**:
      - `+=luminous (add)` https://github.com/Symbian9/azpainter/blob/release/translation/en#L206
      - `+=luminous (dodge)` https://github.com/Symbian9/azpainter/blob/release/translation/en#L207
    - **Removed lines**:
      - none
    - **Fixed lines**:
      - none
  - [x] `ja` | original locale by *Azel*
  - [x] `be` | Cast @antikruk
    - https://github.com/Symbian9/azpainter/issues/58#issuecomment-490206263
  - [ ] `es_ES`
  - [ ] `fr` | Cast @RavengamerSpace
  - [ ] `pt_BR`
  - [ ] `ru` | Cast @danfe
  - [ ] `uk` | *me*
  - [x] `zh_CN` | Cast @SenlinOS
    - https://github.com/Symbian9/azpainter/issues/57
- [ ] Add new locales
  - [x] `fr` by *lbs*
    - https://github.com/Symbian9/azpainter/blob/release/translation/fr
  - (TBA)
- [ ] Update `*.mtr` files for all translations (`!/data/tr/*.mtr`)
- [ ] Update `AUTHORS`
  - https://github.com/Symbian9/azpainter/blob/release/AUTHORS
- [ ] Merge updated locales in `master` branch
  - https://github.com/Symbian9/azpainter/tree/master/translation

**Comment by SenlinOS** [comment]
About the update date:
Time should be written as "2019" (for example, in the AUTHORS file).

**Comment by Symbian9** [comment]
> Time should be written as "2019" (for example, in the AUTHORS file).

Yes, I know. It would be updated this week.

**Comment by Symbian9** [comment]
So, original sources of `v.2.1.4` now merged in `release` branch and is ready for updating translations!

- https://github.com/symbian9/azpainter/tree/release

P.S.: `en`, `ja`, `zh_CN` already updated.

**Comment by antikruk** [comment]
Done
[be.txt](https://github.com/Symbian9/azpainter/files/3154072/be.txt)
Item "Minimize" don't translated in the previous version
![Здымак экрана_2019-05-07_21-31-42](https://user-images.githubusercontent.com/6292989/57324175-0f341e00-7110-11e9-96f7-4ac0ef38682e.png)

**Comment by danfe** [comment]
So, how do we translate these new lines?  I came up with the following, but not 100% sure they are the best:
- luminous (add) -> Яркость (повысить)
- luminous (dodge) -> Яркость (затенить)

Also, there is a missing space in the `be` translation, consider this pseudo-patch:
```diff
@@ -814,7 +814,7 @@
 +=змяніць памер зарэгістраванага пэндзля (пацягнуць улева-ўправа)
 +=усярэднены колер (абярыце 2 кропкі)
 +=змяніць колер (колер, абраны піпеткай -> асноўны)
-+=змяніць колер(колер, абраны піпеткай -> празрысты)
++=змяніць колер (колер, абраны піпеткай -> празрысты)
 +=вылучыць захоплены пласта
 
 1200=вылучыць: чатырохвугольнік
```

**Comment by Symbian9** [comment]
> So, how do we translate these new lines? I came up with the following, but not 100% sure they are the best:

As variant (need take a look in *GIMP* and *Krita* locales)

- luminous (add) -> ~~Яркость (осветлить)~~ Свечение (добавить)
- luminous (dodge) -> ~~Яркость (затенить)~~  Свечение (отнять)

**Comment by danfe** [comment]
If GIMP and Krita are using this terminology, there's no need to differ, fine with me.

**Comment by Symbian9** [comment]
> Also, there is a missing space in the `be` translation, consider this pseudo-patch:

Fixed now in `release` branch.

**Comment by danfe** [comment]
Nice.  It would be even nicer if you could remove trailing whitespace in `pt_BR` and `zh_CN` locales. :-)

**Comment by SenlinOS** [comment]
Japanese (ja) and English (en), they have no spaces. I also did not add space.

**Comment by danfe** [comment]
I didn't say that you have added them, I'm just saying that right now, in this repository, `release` branch, those two files have trailing EOL whitespace on lines 528 and 360, respectively.

**Comment by Symbian9** [comment]
> trailing EOL whitespace on lines 528 (`pt_BR`) and 360 (`zh_CN`)

Fixed in `release`.

**Comment by Symbian9** [comment]
> I also did not add space.

@SenlinOS, You did..., and I not checked it before merging... BTW, it already fixed in `release`.

Here is screenshot of `zh_CN` file from your [zh_CN-Chinese-Translation-for-AzPainter-2.1.4.zip](https://github.com/SenlinOS/warehouse/blob/master/zh_CN-Chinese-Translation-for-AzPainter-2.1.4.zip)

![pic.1](https://i.imgur.com/4zMIfnF.png)

**Comment by SenlinOS** [comment]
> You did..., and I not checked it before merging... BTW, it already fixed in release.

What! I use Leafpad, it doesn't display these extra characters at all.
It's normal to apply zh_CN.mtr, so I haven't found it yet!
Then I also use Geany!

**Comment by SenlinOS** [comment]
![img](https://s2.ax1x.com/2019/05/13/E5gYg1.png)
= v =||| Update again will not appear those extra characters! 
And I'll update my Git warehouse now.

**Comment by Symbian9** [comment]
> Update again will not appear those extra characters!

In *Geany* menu enable "View -> Show White Space"

**Comment by danfe** [comment]
Or try `grep -n '[[:blank:]]$'`, my personal choice. :-)

**Comment by Symbian9** [comment]
> Or try `grep -n '[[:blank:]]$'`, my personal choice. :-)

@danfe, You forget define names/path to files for check in this command.

**Comment by danfe** [comment]
I didn't forget anything, I've simply copied my alias and I also assume that we're not idiots here. :-)

I often use it to check stdin, to defining any files would be bogus in this case.

**Comment by danfe** [comment]
> * luminous (add) -> ~Яркость (осветлить)~ Свечение (добавить)
> * luminous (dodge) -> ~Яркость (затенить)~  Свечение (отнять)

Actually, I happen to like your versions better than mine.  I should have waited for your review before updating FreeBSD port.

**Comment by SenlinOS** [comment]
`Line 360 is just an annotated description and has no specific effect.`

I saw so many "LF" for the first time, thought it was to delete "LF", ha-ha.
I've set up Geany to save the file, automatically removing the trailing whitespace.
OK~OK

**Comment by SenlinOS** [comment]
The translation of AzP 2.1.4 was updated again and the address is unchanged.
9 updates.
![Update Notes](https://github.com/SenlinOS/databox/raw/master/Update-notes.jpg)

**Comment by Symbian9** [comment]
> The translation of AzP 2.1.4 was updated

Also updated in `release` branch.

**Comment by danfe** [comment]
> * luminous (add) -> ~Яркость (осветлить)~ Свечение (добавить)
> * luminous (dodge) -> ~Яркость (затенить)~  Свечение (отнять)

So, if two months later no one came with better alternatives, shall you commit these + their UK/BE versions, and submit all new translations back to Azel so she can include them in 2.1.5?

**Comment by Symbian9** [comment]
> shall you commit these + their UK/BE versions

Yes, but need 1 week (little beasy with other task)

> submit all new translations back to Azel so she can include them in 2.1.5?

I always request Azel to include updates from this GitHub repo ;-)

**Comment by danfe** [comment]
> I always request Azel to include updates from this GitHub repo ;-)

Good, but actually I don't see how well this works in practice.  So far, we had always been updating/fixing the translations **after** she cuts a new release.  It would be nice if she could send us new language strings several days **before**, so we could provide and send her back any fixes, and package maintainers wouldn't have to keep local patches.  For the last few versions, I always had to patch a few strings in the FreeBSD port as a result of our post-release collaborative translation work.

**Comment by Symbian9** [comment]
> I always had to patch a few strings in the FreeBSD port as a result of our post-release collaborative translation work.

I always recommed to use this GitHub releases for packaging instead of patching original Azel's releases ;-)

**Comment by Symbian9** [comment]
I started preparation for packaging. So, If someone want add or fix translation for *AzPainter* `v2.1.4` release - you has 6 hours!*

**Comment by Symbian9** [comment]
Hey, @SenlinOS, are there any additions in @muirmok's Chinese translation that not yet included in `release` repo?

- https://github.com/muirmok/azpainter

**Comment by SenlinOS** [comment]
@Symbian9  There is no new update to @muirmok , she let me continue to maintain Simplified Chinese.

The file has not changed and will be maintained by me.
