### ISSUE TITLE
Packaging AzPainter 2.1.4

### ISSUE THREAD

**Issue by Symbian9** [Symbian9/azpainter#63]
**AzPainter 2.1.4** released (with fixed locales)

- https://github.com/Symbian9/azpainter/releases/tag/v2.1.4

> **NOTE**: Please, rebuild your packages using this release sources!

### PACKAGING STATUS

- https://github.com/Symbian9/azpainter/wiki/Packaging-status

### TODO

Cast *MX Linux* maintainers
- [ ] MX Linux (.deb)
    - http://forum.mxlinux.org/viewtopic.php?f=134&t=51671

Cast @abcang
- [x] macOS
  - https://github.com/abcang/azpainter-mac
  - https://github.com/abcang/homebrew-azpainter

Cast @macports
- [ ] Mac OS (ports)
  - [ ] https://github.com/macports/macports-ports/blob/master/graphics/azpainter/Portfile

Cast @AlexanderP
- [ ] Debian (.deb)
  - http://notesalexp.org/packages/en/jessie/amd64/azpainter/
- [ ] Ubuntu (.deb)
  - https://launchpad.net/~alex-p/+archive/ubuntu/azpainter

Cast @danfe
- [ ] FreeBSD (ports)
  - http://www.freshports.org/graphics/azpainter

Cast @cheshirecatt
- [ ] Solus (.eopkg)
  - https://github.com/cheshirecatt/azpainter-eopkg-package

Cast @void-linux
- [ ] Void Linux (.xbps)
  - https://github.com/void-linux/void-packages/tree/master/srcpkgs/azpainter

Cast @AOSC-Dev
- [ ] AOSC
  - https://packages.aosc.io/packages/azpainter
  - https://github.com/AOSC-Dev/aosc-os-abbs/tree/testing/extra-creativity/azpainter

Cast @aevseev
- [ ] CentOS, OpenSUSE, SLE (.rpm)
  - https://software.opensuse.org/download.html?project=home:aevseev&package=azpainter

***

Cast (?)
- [ ] Arch Linux (AUR)
  - https://aur.archlinux.org/packages/azpainter/

Cast (?)
- [ ] Gentoo (.ebuild)
  - https://gpo.zugaina.org/media-gfx/azpainter

Cast (?)
- [ ] Puppy Linux (.pet/.sfs)
  - http://www.murga-linux.com/puppy/viewtopic.php?t=95329

Cast (?)
- [ ] SliTaZ (.tazpkg)
  - http://forum.slitaz.org/topic/azpainter-why-it-isnt-in-slitaz-repositories

Cast (?)
- [ ] Slackware (.tgz/.txz)

### REFERENCES

- https://repology.org/project/azpainter/versions
- https://www.linux.org.ru/forum/multimedia/13223232

**Comment by dtzWill** [comment]
Packaged for NixOS: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/azpainter/default.nix, FWIW! :)

**Comment by Symbian9** [comment]
> Packaged for NixOS

COOL & Thanks!

**Comment by Symbian9** [comment]
Next call for packaging would be created after *AzPainter* `v2.1.5` translating would be completed

- https://github.com/Symbian9/azpainter/issues/69
