### ISSUE TITLE
Translating AzPainter 2.1.5

### ISSUE THREAD

**Issue by Symbian9** [Symbian9/azpainter#69]
*AzPainter 2.1.5* released (2019/11/30)

- Original - https://osdn.net/projects/azpainter/releases/71988
  - http://osdn.dl.osdn.jp/azpainter/71988/azpainter-2.1.5.tar.xz
- Fixes - https://github.com/Symbian9/azpainter/tree/release

### FAQ

- https://github.com/Symbian9/azpainter/blob/master/translation/HOWTO_en

Translation template (`en` is plain text file; in English)

- https://github.com/Symbian9/azpainter/blob/release/translation/en

Language ID (translation; locale) naming:

- http://www.localeplanet.com/icu/

> **NOTE**: Currently working branch is `release`, so firstly all patches should be included in `release` branch and then it will be merged into `master` for package maintainers.
>
> - https://github.com/Symbian9/azpainter/tree/release/translation/

### TODO

> **ATTENTION**: Translation files should NOT include "white spaces"! Check it using `grep`:.
> 
> ```
> $ grep -n '[[:blank:]]$'
> ```

- [x] Check existing locales
  - [x] `en` | original locale by @azelpg with fixes by *me*: **this is translation template**!
    - **New lines**:
      - none
    - **Removed lines**:
      - none
    - **Fixed lines**:
      -  https://github.com/Symbian9/azpainter/commit/759110d5614ff6f7138fd8ddb51f18f557b3c880
  - [x] `ja` | original locale by @azelpg
  - [ ] `be` | Cast @antikruk
  - [x] `es_ES` | Cast @cheshirecatt
  - [ ] `fr`
  - [ ] `pt_BR`
  - [ ] `ru` | Cast @danfe
  - [ ] `uk` | /me
  - [x] `zh_CN` | Cast @SenlinOS
    - https://github.com/SenlinOS/warehouse/commit/aca341638186f91e990f70259eeb0aee7ca27d74
- [x] Add new locales
  - [x] `it` by *Nihiles*
    - https://github.com/Symbian9/azpainter/blob/release/translation/it
  - (TBA)
- [ ] Update `*.mtr` files for all translations (`!/data/tr/*.mtr`)
- [ ] Update `AUTHORS`
  - https://github.com/Symbian9/azpainter/blob/release/AUTHORS
- [ ] Merge updated locales in `master` branch
  - https://github.com/Symbian9/azpainter/tree/master/translation

**Comment by danfe** [comment]
Apparently, only Chinese translations were merged by Azel from 2.1.4, others are the same.  Something went wrong here, as we should only only translating new strings (or fixing poorly translated old ones).

**Comment by Symbian9** [comment]
> Apparently, only Chinese translations were merged by Azel from 2.1.4, others are the same.

Seems like @azelpg not merged our fixes from 2.1.4, so I just left locales as it already in `master` branch.

To update each locale translator should manually use `en` as template from `release` branch.

- https://github.com/Symbian9/azpainter/commit/759110d5614ff6f7138fd8ddb51f18f557b3c880
  -  https://github.com/Symbian9/azpainter/blob/release/translation/en

Also, Azel's each official release (in most cases) include only updated locales from previous release (as at this moment we translate after each release; that is why I maintain this repo for package maintainers)

**Comment by Symbian9** [comment]
Only for testing purposes, there are already DEB packages for Ubuntu/Debian

- https://launchpad.net/~alex-p/+archive/ubuntu/azpainter
- https://notesalexp.org/packages/en/stretch/amd64/azpainter/

FTR, It would be updated also when all locales would be fixed.

**Comment by danfe** [comment]
Unless I'm mistaken there are no differences between `translations/en` file from Azel's 2.1.5 release and this repo, which means there are no new strings and you can call for packagers.  I'm currently updating the FreeBSD port.

**Comment by Symbian9** [comment]
> Unless I'm mistaken there are no differences between translations/en file from Azel's 2.1.5 release and this repo, which means there are no new strings and you can call for packagers.

Okay

- Packaging AzPainter 2.1.5 https://github.com/Symbian9/azpainter/issues/71

BTW, I think, fixing locales should be first task.

**Comment by danfe** [comment]
Well yeah, my point that that per what I see, your repo contains all the latest changes which Azel should have included in 2.1.5, but for some reason she did not.  I did not find any new strings between 2.1.4 and 2.1.5.

**Comment by Symbian9** [comment]
> I did not find any new strings between 2.1.4 and 2.1.5.

No new lines, but one extended line

- https://github.com/Symbian9/azpainter/commit/759110d5614ff6f7138fd8ddb51f18f557b3c880

**Comment by Symbian9** [comment]
**ATTENTION!** Lets update locales for *AzPainter* `2.1.6`!

- https://github.com/Symbian9/azpainter/issues/84
