### ISSUE TITLE
Packaging AzPainter 2.1.5

### ISSUE THREAD

**Issue by Symbian9** [Symbian9/azpainter#71]
**AzPainter 2.1.5** released (with fixed locales)

- https://github.com/Symbian9/azpainter/releases/tag/v2.1.5

> **NOTE**: Please, rebuild your packages using this release sources!

### PACKAGING STATUS

- https://github.com/Symbian9/azpainter/wiki/Packaging-status

### TODO

Cast @abcang
- [x] Mac OS / macOS
  - https://github.com/abcang/azpainter-mac
  - https://github.com/abcang/homebrew-azpainter

Cast @macports
- [ ] Mac OS / macOS (ports)
  - [ ] https://github.com/macports/macports-ports/blob/master/graphics/azpainter/Portfile

Cast @danfe
- [x] FreeBSD (ports)
  - http://www.freshports.org/graphics/azpainter

Cast @ibara
- [x] OpenBSD (ports)
  - https://github.com/openbsd/ports/tree/master/graphics/azpainter

Cast @AlexanderP
- [x] Debian (.deb)
  - http://notesalexp.org/packages/en/jessie/amd64/azpainter/
- [x] Ubuntu (.deb)
  - https://launchpad.net/~alex-p/+archive/ubuntu/azpainter

Cast *MX Linux* maintainers
- [ ] MX Linux (.deb)
    - http://forum.mxlinux.org/viewtopic.php?f=134&t=51671

Cast @dtzWill
- [ ] NixOS
  - https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/azpainter/default.nix

Cast @cheshirecatt
- [x] Solus (.eopkg)
  - https://github.com/cheshirecatt/azpainter-eopkg-package

Cast @void-linux
- [x] Void Linux (.xbps)
  - https://github.com/void-linux/void-packages/tree/master/srcpkgs/azpainter

Cast @AOSC-Dev
- [ ] AOSC
  - https://packages.aosc.io/packages/azpainter
  - https://github.com/AOSC-Dev/aosc-os-abbs/tree/testing/extra-creativity/azpainter

Cast @aevseev
- [ ] CentOS, OpenSUSE, SLE (.rpm)
  - https://software.opensuse.org/download.html?project=home:aevseev&package=azpainter

***

Cast (?)
- [ ] Arch Linux (AUR)
  - https://aur.archlinux.org/packages/azpainter/

Cast (?)
- [x] Gentoo (.ebuild)
  - https://gpo.zugaina.org/media-gfx/azpainter

Cast (?)
- [ ] Puppy Linux (.pet/.sfs)
  - http://www.murga-linux.com/puppy/viewtopic.php?t=95329

Cast (?)
- [ ] SliTaZ (.tazpkg)
  - http://forum.slitaz.org/topic/azpainter-why-it-isnt-in-slitaz-repositories

Cast (?)
- [ ] Slackware (.tgz/.txz)

**Comment by Symbian9** [comment]
FTR, `master` just got hot-fix that should solve some architecture specific issue (*PowerPC*, *ARM*, etc.)

- https://github.com/Symbian9/azpainter/commit/2564ee559d3aa9a1351f56c6b4c7395c419d288b

**Comment by ibara** [comment]
Thanks. I'll remove those patches from our local package once 2.1.5 get published.

**Comment by danfe** [comment]
Thanks, I've added the patch to the FreeBSD port.

**Comment by Symbian9** [comment]
@sikmir, may I ask you for fix Nix package to use patches from my repo?

- https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/azpainter/default.nix

Also, could you setup MacPorts using next repos:

- https://github.com/abcang/azpainter-mac
- https://github.com/abcang/homebrew-azpainter

**Comment by sikmir** [comment]
> @sikmir, may I ask you for fix Nix package to use patches from my repo?
> 
>     * https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/azpainter/default.nix
> 

PR to nixpkgs is aready created https://github.com/NixOS/nixpkgs/pull/75027.

**Comment by Symbian9** [comment]
***Lets package AzPainter 2.1.6!*** https://github.com/Symbian9/azpainter/issues/87
