### ISSUE TITLE
Translating AzPainter 2.1.6

### ISSUE THREAD

**Issue by Symbian9** [Symbian9/azpainter#84]
*AzPainter 2.1.6* released (2020/04/20)

- Original - https://github.com/azelpg/azpainter/tree/master
- For contributing updates - https://github.com/Symbian9/azpainter/tree/dev

### FAQ

- https://github.com/Symbian9/azpainter/blob/master/translation/HOWTO_en

Translation template (`en` is plain text file; in English)

- https://github.com/Symbian9/azpainter/blob/release/translation/en

Language ID (translation; locale) naming:

- http://www.localeplanet.com/icu/

> **NOTE**: Currently working branch is `dev`, so firstly all patches should be included in `release` branch and then it will be merged into `master` for package maintainers.
>
> - https://github.com/Symbian9/azpainter/tree/dev/translation/

### TODO

> **ATTENTION**: Translation files should NOT include "white spaces"! Check it using `grep`:.
> 
> ```
> $ grep -n '[[:blank:]]$'
> ```

- [x] Check existing locales
  - [x] `en` | original locale by @azelpg with fixes by *me*: **this is translation template**!
    - **New lines**:
      - none
    - **Removed lines**:
      - none
    - **Fixed lines**:
      -  none
  - [x] `ja` | original locale by @azelpg
  - [ ] `be` | Cast @antikruk
  - [x] `es_ES` | Cast @cheshirecatt
  - [ ] `fr`
  - [x] `it` by *Nihiles*
  - [ ] `pt_BR`
  - [ ] `ru` | Cast @danfe
  - [ ] `uk` | /me
  - [x] `zh_CN` | Cast @SenlinOS
- [ ] Add new locales
  - (TBA)
- [ ] Update `*.mtr` files for all translations (`!/data/tr/*.mtr`)
- [ ] Update `AUTHORS`
  - https://github.com/Symbian9/azpainter/blob/release/AUTHORS
- [ ] Merge updated locales in `master` branch
  - https://github.com/Symbian9/azpainter/tree/master/translation

**Comment by Symbian9** [comment]
**NOTE:** Actually there are NO new strings in comparison to AzPainter `2.1.5`!

So, for AzPainter `2.1.6` update only those locales which not updated for previous releases!

**Comment by danfe** [comment]
Now, Azel's EN locale is more complete than the one in this repo.  Consider merging the following patch:
```patch
@@ -1261,7 +1261,7 @@
 +=All opaque to perfect opaque
 +=HLS adjustment...
 
-### 表示
+### View
 6000=Panel(&P)
 +=Canvas flip horizontally(&Q)
 +=Show background as check pattern(&K)
@@ -1298,7 +1298,7 @@
 +=180 degree
 +=270 degree
 
-### 設定ほか
+### Setting
 7000=Environment setting(&E)...
 +=Grid setting(&G)...
 +=Shortcut key setting(&K)...
```

**Comment by Symbian9** [comment]
> Now, Azel's EN locale is more complete than the one in this repo.

Are you sure that you are looking inside `dev` branch? All those patches from Azel already merged here:

- https://github.com/Symbian9/azpainter/blob/dev/translation/en#L1275
- https://github.com/Symbian9/azpainter/blob/dev/translation/en#L1301

**Comment by danfe** [comment]
Ah, you're right, I was on `master`, sorry.  I'm not very good with Git and all this branches business, unfortunately. :-(

**Comment by Symbian9** [comment]
>  I'm not very good with Git and all this branches

There was my mistake in this issue header comment, now link to translation template fixed to `dev`.

**Comment by Symbian9** [comment]
**NOTE:** Tomorrow I will start packaging, so check your locales if some of you not did it yet!

**Comment by antikruk** [comment]
Hi
[be.txt](https://github.com/Symbian9/azpainter/files/4638307/be.txt)

**Comment by blue-devil-93** [comment]
[de_DE.txt](https://github.com/Symbian9/azpainter/files/4988101/de_DE.txt) 
Note: This file has already been send to the email address of the author of this application.

**Comment by danfe** [comment]
So, long time no talk. :-)  AzPainter development now happens on GitLab, the latest version is 3.0.5 already.  If there are still plans to provide and support CIS languages, it would be harder now as she apparently had dropped all translations except English, Japanese, Chinese, and Brazilian.

**Comment by blue-devil-93** [comment]
I'll look after it. Maybe i can submitt a new merge request for german
language there. Can take some time.
