### ISSUE TITLE
Packaging AzPainter 2.1.6

### ISSUE THREAD

**Issue by Symbian9** [Symbian9/azpainter#87]
**AzPainter 2.1.6** released (with fixed locales)

- https://github.com/Symbian9/azpainter/releases/tag/v2.1.6

> **NOTE**: Please, rebuild your packages using this release sources!

### PACKAGING STATUS

- https://github.com/Symbian9/azpainter/wiki/Packaging-status

### TODO

Cast @xeffyr
- [ ] Android / Termux (X11-packages)
  - https://github.com/termux/x11-packages/tree/master/packages/azpainter

Cast @abcang
- [ ] Mac OS / macOS
  - https://github.com/abcang/azpainter-mac
  - https://github.com/abcang/homebrew-azpainter

Cast @macports
- [ ] Mac OS / macOS (ports)
  - [ ] https://github.com/macports/macports-ports/blob/master/graphics/azpainter/Portfile

Cast @danfe
- [ ] FreeBSD (ports)
  - http://www.freshports.org/graphics/azpainter

Cast @ibara
- [ ] OpenBSD (ports)
  - https://github.com/openbsd/ports/tree/master/graphics/azpainter

Cast @AlexanderP
- [ ] Debian (.deb)
  - http://notesalexp.org/packages/en/jessie/amd64/azpainter/
- [ ] Ubuntu (.deb)
  - https://launchpad.net/~alex-p/+archive/ubuntu/azpainter

Cast *MX Linux* maintainers
- [ ] MX Linux (.deb)
    - http://forum.mxlinux.org/viewtopic.php?f=134&t=51671

Cast @dtzWill
- [ ] NixOS
  - https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/azpainter/default.nix

Cast @cheshirecatt
- [ ] Solus (.eopkg)
  - https://github.com/cheshirecatt/azpainter-eopkg-package

Cast @void-linux
- [ ] Void Linux (.xbps)
  - https://github.com/void-linux/void-packages/tree/master/srcpkgs/azpainter

Cast @AOSC-Dev
- [ ] AOSC
  - https://packages.aosc.io/packages/azpainter
  - https://github.com/AOSC-Dev/aosc-os-abbs/tree/testing/extra-creativity/azpainter

Cast @aevseev
- [ ] CentOS, OpenSUSE, SLE (.rpm)
  - https://software.opensuse.org/download.html?project=home:aevseev&package=azpainter

***

Cast (?)
- [ ] Arch Linux (AUR)
  - https://aur.archlinux.org/packages/azpainter/

Cast (?)
- [x] Gentoo (.ebuild)
  - https://gpo.zugaina.org/media-gfx/azpainter

Cast (?)
- [ ] Puppy Linux (.pet/.sfs)
  - http://www.murga-linux.com/puppy/viewtopic.php?t=95329

Cast (?)
- [ ] SliTaZ (.tazpkg)
  - http://forum.slitaz.org/topic/azpainter-why-it-isnt-in-slitaz-repositories

Cast (?)
- [ ] Slackware (.tgz/.txz)

**Comment by sikmir** [comment]
@Symbian9 Maybe I missed something, but what is wrong with original [azpainter](https://github.com/azelpg/azpainter) repo? Why package maintainers use this one instead?

**Comment by danfe** [comment]
@sikmir I've always considered this repo as where translation coordination happens.  I didn't even know that Azel is here on GitHub.  I'm using her official tarballs she publishes on OSDN for packaging.

**Comment by Symbian9** [comment]
> Why package maintainers use this one instead?
>
> I didn't even know that Azel is here on GitHub.

Because this this repo include latest locales update & I actively maintain issues tracker & translations, packaging tasks.

@danfe @sikmir Azel's repo NOT ready yet! See - https://github.com/Symbian9/azpainter/issues/81

**Comment by ibara** [comment]
Opened #88 to track a bug that affects packaging.

**Comment by Symbian9** [comment]
> Opened #88 and #89 to track bugs that affect packaging.

According to #88, as `v2.1.6` release (`master` branch) came with signification changes in `Makefile.in` & `configure` files highly recommend maintainers to review/rewrite their previous build scripts configuration to meet latest changes.

**Comment by ibara** [comment]
> > Opened #88 and #89 to track bugs that affect packaging.
> 
> According to #88, as `v2.1.6` release (`master` branch) came with signification changes in `Makefile.in` & `configure` files highly recommend maintainers to review/rewrite their previous build scripts configuration to meet latest changes.

Sure, and I have. But that's not actually the issue in #88. The issue is that the configure script is broken. It claims to support environment variables, but it in fact does not (you cannot do something like `env CFLAGS='-O3' ./configure`, it will not work). It accepts some non-standard arguments (CC, CFLAGS, etc.) and even then, does not support those non-standard arguments correctly (since `./configure CFLAGS="-O2 -pipe"` is broken as well).

If not using autotools is desired, my autotools-less configure script for oksh does support environment variables correctly:
https://github.com/ibara/oksh/blob/master/configure

**Comment by ibara** [comment]
OpenBSD is packaged. However, it will not be able to be committed until after OpenBSD 6.7 has been released in a few weeks.

**Comment by Symbian9** [comment]
**UPD**: Additional patch to package `v2.1.6` for some architectures (like *PowerPC* and *ARM*) just merged into `master`:

- https://github.com/Symbian9/azpainter/commit/87ef813c0d8a62e7928b4832ca3a2606860be3c7

Apply it (if needed) for your maintained AzPainter `v2.1.6` packages.

Hopefully, `v2.1.7` would come soon with this patch already merged as part of release tarball.

**Comment by sikmir** [comment]
Created PR https://github.com/NixOS/nixpkgs/pull/86028

**Comment by Symbian9** [comment]
**UPD2:** Additional patch to package `v2.1.6` just merged into `master`:

- https://github.com/Symbian9/azpainter/commit/0c91d4650b57992cc857913804fead5afd0fce51
  - Fix `configure`
  - Fix build instruction for Mac OS (see `README` & `README_ja`):
    - ```
      $ ./configure --prefix=/opt/X11
      $ make
      $ sudo make install
      ```
P.S. @azelpg, maybe we should skip `v2.1.6` packaging & immediately roll out `v2.1.7` (basing on actual [`master`](https://github.com/Symbian9/azpainter/tree/master) branch) due to latest changes?

**Comment by azelpg** [comment]
The version does not change, so please treat the latest version as 2.1.6

**Comment by Symbian9** [comment]
> The version does not change, so please treat the latest version as 2.1.6

OK.

JFTR, Problem was with `v2.1.6` release tarball on OSDN - it changed few times, that is bad practice, because if something released any changes & updates should go into next release; replacing release tarball with another one is bad idea.

**Comment by Symbian9** [comment]
**UPD3:** Azel moved all official source downloads to *own website* (and removed their official repos from GitHub & OSDN):

- http://azsky2.html.xdomain.jp/arc/download.html

If you prefer use official tarball for packaging AzPainter `v2.1.6` and add optional patches, here is official `v2.1.6` tarball:

- http://azsky2.html.xdomain.jp/arc/azpainter-2.1.6-200428.tar.xz | MD5: `28486ba31fb2d0e6bcda42a1fbf775dc`

Instead use release tarball from this repo (which include updated & fixed locales):

- https://github.com/Symbian9/azpainter/releases/tag/v2.1.6

***BTW***, I highly recommend also apply latest patches (which are especially useful for some architectures support) from `master` branch:

- https://github.com/Symbian9/azpainter/tree/master

**Comment by lanodan** [comment]
Gentoo is maintained by myself in GURU (Gentoo community repository), which I just updated to 2.1.6.

**Comment by Symbian9** [comment]
> which I just updated to 2.1.6.

Great! Thank You, @lanodan!

**Comment by Vouivre** [comment]
Hi, now I can use azpainter without problem. So I have packaged it for KISS Linux. 

https://github.com/kisslinux/community/tree/master/community/azpainter

**Comment by Symbian9** [comment]
>  packaged it for KISS Linux

It's great! Thank you, @Vouivre!

**Comment by danfe** [comment]
FYI the latest version is 2.1.7b4, however, it still lacks some translation patches which should be included before packaging it.

**Comment by lanodan** [comment]
Ah yeah, looks azel moved from Github to their own website, which sadly doesn't seems to have something like an RSS/Atom feed or mailing-list version of <http://azsky2.html.xdomain.jp/arc/update.html>.

**Comment by Symbian9** [comment]
> FYI the latest version is 2.1.7b4, however, it still lacks some translation patches which should be included before packaging it.

Yeah, I know, but `2.1.7b4` is still "beta", so when *Azel* would release `2.1.7` I'll create new task for translators & packagers.

FTR, @julianaito, could you take a look on `2.1.7b4` — does "*signed char*" already fixed by *Azel*?

- http://azsky2.html.xdomain.jp/arc/azpainter-2.1.7b4.tar.xz

**Comment by danfe** [comment]
> 2.1.7b4 — does "signed char" already fixed by Azel?

Yes, those were fixed or changed to _int_ when it was more suitable.

**Comment by julianaito** [comment]
Hi,

It builds and works fine on macppc without the signed char patches. Note that clang-10 emits: 

```
include/mEvent.h:120:2: warning: redefinition of typedef 'mEvent' is a C11 feature [-Wtypedef-
redefinition]
```
(there are more of them)

You may want to bump the `std=gnu99` to `std=gnu11`, because it may croak with old gcc-4 compilers.

(fyi @ibara)
